api/api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('core.urls','core'), namespace='core')),
    path('', include(('clipping.urls','clipping'), namespace='clipping')),
]

api/clipping/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'clipping'

urlpatterns = [
	path('create_clipping/', views.ClippingCreate.as_view(), name='create_clipping'),
	path('update_clipping/<int:pk>/', views.ClippingUpdate.as_view(), name='update_clipping'),
	path('remove_clipping/<int:pk>/', views.ClippingDelete.as_view(), name='remove_clipping'),
	path('list_clipping/', views.ClippingListView.as_view(), name='list_clipping'),
	path('create_parser/', views.ParserView.as_view(), name='parser')
]

api/core/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

app_name = 'core'

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name="index.html"), name="login"),
    path('sair/', auth_views.LogoutView.as_view(next_page="core:login"), name="logout"),
]

api/clipping/models.py
from django.db import models
from django.contrib.auth.models import User

class Autor(models.Model):
	nome = models.CharField('Nome', max_length=100)
	data_criacao = models.DateTimeField(auto_now_add=True)
	data_atualizacao = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.nome

	class Meta:
		verbose_name = 'Autor'
		verbose_name_plural = 'Autores'

class Livro(models.Model):
	titulo = models.CharField('Título', max_length=200)
	autor = models.ForeignKey(Autor, on_delete=models.PROTECT, related_name='livro', verbose_name='Autor')
	data_criacao = models.DateTimeField(auto_now_add=True)
	data_atualizacao = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.titulo

	class Meta:
		verbose_name = 'Livro'
		verbose_name_plural = 'Livros'

class Recorte(models.Model):
	texto = models.TextField('Recorte')
	data_criacao = models.DateTimeField(auto_now_add=True)
	data_atualizacao = models.DateTimeField(auto_now=True)
	posicao = models.CharField('Posição/Página', null=True, blank=True, max_length=10)

	user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='recorte', verbose_name='Usuario')
	livro = models.ForeignKey(Livro, on_delete=models.PROTECT, related_name='recorte', verbose_name='Livro')
	autor = models.ForeignKey(Autor, on_delete=models.PROTECT, related_name='recorte', verbose_name='Autor')

	class Meta:
		verbose_name = 'Recorte'
		verbose_name_plural = 'Recortes'

api/core/models.py
from django.db import models

# Create your models here.

api/clipping/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from django.db import transaction

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from django.http import JsonResponse

from django.contrib.auth.models import User
from . import models
from .clipping import *


class ClippingSave():
	model = models.Recorte
	fields = ['texto', 'autor', 'livro', 'posicao']
	template_name = 'create_clipping.html'
	success_url = reverse_lazy('core:home')


class ClippingCreate(LoginRequiredMixin, ClippingSave, CreateView):

	def form_valid(self, form):
		clipping = form.save(commit=False)
		clipping.user = self.request.user
		clipping.save()
		return super(ClippingSave, self).form_valid(form)

class ClippingUpdate(LoginRequiredMixin, ClippingSave, UpdateView):
	pass

class ClippingDelete(LoginRequiredMixin, DeleteView):
    model = models.Recorte
    success_url = reverse_lazy('core:home')
    template_name = 'clipping_confirm_delete.html'

@method_decorator(cache_page(60 * 5), name='dispatch')
class ClippingListView(LoginRequiredMixin, ListView):

	template_name = 'list_clipping.html'
	model = models.Recorte
	cache_timeout = 60

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['user'] = self.request.user
		return context

	def get_queryset(self):
		queryset = models.Recorte.objects.filter(user=self.request.user)
		return queryset

class ParserView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "parser.html")

    def post(self, request):
        document = request.POST["content"]
        clippings = split_document(document)
        data = []
        with transaction.atomic():
            for clipping in clippings:
                name, author, page, position, date, content = extract_clipping(clipping)
                autor_object, _ = models.Autor.objects.get_or_create(nome=author)
                livro_object, _ = models.Livro.objects.get_or_create(titulo=name, autor=autor_object)
                recorte_object = models.Recorte.objects.create(
                    livro=livro_object, \
                    autor=autor_object, \
                    posicao=position, \
                    user=request.user, \
                    texto=content
                )
                data.append({
                    "livro": name,
                    "autor": author,
                    "posicao": position,
                    "texto": content
                })

        if request.is_ajax:
            return JsonResponse(data, safe=False)
        

api/core/views.py
from django.shortcuts import render

# Create your views here.

api/clipping/templates/clipping_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Você tem certeza que deseja deletar "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

api/clipping/templates/clipping_update_form.html
{% extends "base.html" %}
{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock %}

api/clipping/templates/create_clipping.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<div class="col-sm-12 col-md-10 col-lg-8 mx-auto">
    <form method="post">{% csrf_token %}
        <div class="row">
            <div class="col-md-6 col-sm-12">
                {{ form.texto|as_crispy_field }}
            </div>
            <div class="col-md-6 col-sm-12">
                {{ form.autor|as_crispy_field }}
                {{ form.livro|as_crispy_field }}
                {{ form.posicao|as_crispy_field }}
            </div>
        </div>            
        <input type="submit" class="btn btn-primary" value="Save">
    </form>
</div>
{% endblock %}

{% block js %}

{% endblock %}

api/clipping/templates/list_clipping.html
{% extends "base.html" %}

{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/list_clipping.css' %}">
{% endblock %}

{% block content %}
<div class="container col-sm-12 col-md-10 col-lg-8 mx-auto px-0 my-2">
  <div class="card-columns">
    {% for object in object_list %}
    <div class="card">
      <img class="card-img-top img-fluid" id={{ object.autor }} alt="">
      <div class="card-body text-dark">
      <blockquote class="card-bodyquote">
        {{ object.texto }}
      </blockquote>
      </div> 
        <div class="card-footer">
          <div class="row">
            <div class="col-sm-12 col-md-8 text-muted">
                <small>
                  {{ object.livro }} de {{ object.autor }}, posição {{ object.posicao }}
                </small>
            </div>
            <div class="col-sm-12 col-md-4 text-md-right text-center small">
              <a href="{% url "clipping:update_clipping" object.pk %}" data-toggle="tooltip" title="Editar"><i class="fa fa-edit"></i></i></a>
              <a href="{% url "clipping:remove_clipping" object.pk %}" data-toggle="tooltip" title="Excluir"><i class="fa fa-trash"></i></a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
</div>

{% endblock %}

{% block js %}
<script src="{% static 'js/get_images.js' %}"> 
</script>
{% endblock %}

api/clipping/templates/parser.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/parser.css' %}">
{% endblock %}
{% block content %}
    {% csrf_token %}
    <div class="container vertical-center">
        <div class="row">
            Você pode importar recortes a partir de um arquivo, que deve possuir o formato abaixo.
        </div>
        <div class="row">
            <textarea>
Harry Potter e o Cálice de Fogo (J. K. Rowling)
- Seu marcador na página 450 | posição 6893 | Adicionado: segunda-feira, 27 de março de 2017 19:40:08


==========
Harry Potter e o Cálice de Fogo (J. K. Rowling)
- Seu marcador na página 503 | posição 7705 | Adicionado: terça-feira, 28 de março de 2017 09:13:43
            </textarea> 
        </div>
        <div class="row">
            Importe seu arquivo: <input type="file" id="input-file" name="input-file" accept="text/">
        </div>
{% endblock %}

{% block js %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
{% load static %}
<script src="{% static 'js/parser.js' %}"></script>
{% endblock %}

api/core/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/all.css' integrity='sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU' crossorigin='anonymous'>
  {% block css %}
  {% endblock %}
  <title>{% block title %}Partorum{% endblock %}</title>
</head>
<body style="background-color:brown; color: white">
  {% load cache %}
  {% cache 500 navbar %}
    <nav class="navbar  navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'core:home' %}"><i class="fa fa-bookmark" aria-hidden="true"></i>Partorum</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'clipping:list_clipping' %}">Recortes <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'clipping:create_clipping' %}">Criar Recorte</a>
            <a class="nav-item nav-link" href="{% url 'clipping:parser' %}">Importar Recortes</a>
            <a class="nav-item nav-link " href="{% url 'core:logout' %}">logout</a>
          </div>
        </div>
      </nav>
  {% endcache %}
  <main>
    {% block content %}
    {% endblock %}
  </main>
  {% block js %}
  {% endblock %}
</body>
</html>

api/core/templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% block title %}Home{% endblock %}

{% block content %}
  <div class="container vertical-center">
    {% if user.is_authenticated %}
      Olá {{ user.username }}!
    {% else %}
      <h2>Olá :)</h2>
    {% endif %}
    <h3>O que é <strong>Partorum</strong></h3>
    <p>Partorum é uma plataforma onde você pode guardar todas as anotações do seus livros favoritos ;)</p>


  {% if user.is_authenticated %}
    <div class="row">
      <div class="col">
        <p><a class="btn btn-primary" href="{% url 'clipping:list_clipping' %}">Lista de recortes</a></p>
      </div>
      <div class="col">
        <p><a class="btn btn-primary" href="{% url 'clipping:create_clipping' %}">Cadastrar um novo recorte</a></p>
      </div>
      <div class="col">
        <p><a class="btn btn-primary" href="{% url 'clipping:parser' %}">Importar recortes</a></p>
      </div>
      <div class="col">     
        <p><a class="btn btn-primary" href="{% url 'core:logout' %}">logout</a></p>
      </div>
    </div>
  {% else %}
  <div class="row">
    <a class="btn btn-primary" href="{% url 'core:login' %}">Login</a>
  </div>
  {% endif %}
</div>
{% endblock %}

api/core/templates/index.html
<!-- templates/registration/login.html -->
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block title %}Login{% endblock %}

{% block content %}
<div class="col-sm-12 col-md-8 col-lg-6 mx-auto">
  <form method="post">
    {% csrf_token %}
    {{ form|crispy}}
    <button type="submit">Login</button>
  </form>
</div>
{% endblock %}